[package]
name = "cargo-local-registry"
version = "0.2.8"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["cargo-subcommand"]
repository = "https://github.com/dhovart/cargo-local-registry"
homepage = "https://github.com/dhovart/cargo-local-registry"
description = """
A Cargo subcommand for managing local registries.
"""
edition = "2024"

[lints.rust]
warnings = "deny"

[lints.clippy]
all = "deny"

[dependencies]
anyhow = "1.0.47"
axum = "0.8.6"
bytes = "1.10.1"
cargo = "0.89.0"
cargo-platform = "0.3.0"
clap = { version = "4.5.41", features = ["derive"] }
env_logger = "0.11.8"
flate2 = "1.1.2"
futures = "0.3.31"
openssl = { version = '0.10.73', optional = true }
rayon = "1.8.0"
serde = { version = "1.0.104", features = ['derive'] }
serde_json = "1.0.141"
tar = "0.4.26"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "fs"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
url = "2.1.1"
reqwest = { version = "0.12", features = ["json", "stream"] }
semver = "1.0"

[dev-dependencies]
tempfile = "3.1.0"

[features]
vendored-openssl = ['openssl/vendored']
